spring:
  datasource:
    url: jdbc:mysql://localhost:3306/flance_elearning?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

flance:
  tx:
    netty-server-ip: 127.0.0.1
    netty-server-port: 8899
    netty-server-id: flance-tx-center-001
    load-balance-server-ip: 127.0.0.1
    load-balance-server-port: 80


mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
