flance:
  tx:
    enabled: true
    enable-datasource-proxy: true
    server-module: netty
    tx-server-ip: 127.0.0.1
    tx-server-port: 8899
    tx-server-re-try-times: 5
    client:
      enabled: true
      netty-client-id: flance-tx-demo1
      netty-client-ip: 127.0.0.1
      netty-client-port: 8081

  binlog:
    host: 127.0.0.1
    port: 3306
    schema: flance_elearning
    tables: sys_flance_api,flance_test
    listener-class: com.flance.jdbc.binlog.listener.LogListener
    module: multi
    username: root
    password: root
    server-id: 1