flance:
  tx:
    enabled: true
    enable-datasource-proxy: true
    application-id: flance-tx-demo1
    server-module: netty

server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/flance_elearning?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
